export const SAVE_USERINFO = 'GET_USERINFO'

export const SAVE_LIST = 'GET_LIST'

export const SAVE_ARTICLELIST = 'GET_ARTICLELIST'

export const SAVE_DYNAMICLIST = 'GET_DYNAMICLIST'

export const SAVE_SEARCH_LIST = 'SAVE_SEARCH_LIST'

export const CLEAN_SEARCH_LIST = 'CLEAN_SEARCH_LIST'

export const SAVE_TEMP = 'SAVE_TEMP'

export const UP_LIST_PAGE = 'UP_LIST_PAGE'

export const UP_ARTICLE_LIST_PAGE = 'UP_ARTICLE_LIST_PAGE'

export const UP_DYNAMIC_LIST_PAGE = 'UP_DYNAMIC_LIST_PAGE'

export const UP_SEARCH_LIST_PAGE = 'UP_SEARCH_LIST_PAGE'
